export enum BlogType {
  Blague = 'Blague',
  Question = 'Question',
  Conseil = 'Conseil',
  Recommandation = 'Recommandation'
}

export class Blog {
  id!: string; // Optional because it might be generated by the backend
  title!: string;
  type!: BlogType;
  content!: string;
  date!: string;
}
